"use client";

import { useEffect, useRef, useState } from "react";
import { createJourneyMemory, getIsland, HomerScene, HomerTransition, ISLANDS, JourneyCard, JourneyMemory, JourneySummary, resolveIsland } from "../lib/journey";

type Phase = "map" | "loading" | "island" | "resolving" | "ending" | "generating_end";
type AudioStatus = "idle" | "loading" | "ready" | "playing" | "error";
interface SavedJourney { goal: string; phase: Phase; memory: JourneyMemory | null; scene: HomerScene | null; answer: string; resolution: string; summary: JourneySummary | null; card: JourneyCard | null; }
const SESSION_KEY = "odyssey.fourteen-islands.v1";
const ISLAND_ART: Record<string, string> = {
  troy: "/islands/troy.webp", cicones: "/islands/cicones.webp", "lotus-eaters": "/islands/lotus-eaters.webp",
  cyclops: "/islands/cyclops.webp", aeolus: "/islands/aeolus.webp", laestrygonians: "/islands/laestrygonians.webp",
  circe: "/islands/circe.webp", underworld: "/islands/underworld.webp", sirens: "/islands/sirens.webp",
  "scylla-charybdis": "/islands/scylla-charybdis.webp", "helios-cattle": "/islands/helios-cattle.webp",
  calypso: "/islands/calypso.webp", phaeacia: "/islands/phaeacia.webp", ithaca: "/islands/ithaca.webp",
};

async function requestHomer<T>(payload: object): Promise<T> {
  const response = await fetch("/api/homer", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
  const data = await response.json();
  if (!response.ok) { const error = new Error(data.message || "The sea has not answered."); Object.assign(error, { requestId: data.requestId }); throw error; }
  return data as T;
}

export default function Home() {
  const [goal, setGoal] = useState(""); const [phase, setPhase] = useState<Phase>("map"); const [memory, setMemory] = useState<JourneyMemory | null>(null);
  const [scene, setScene] = useState<HomerScene | null>(null); const [answer, setAnswer] = useState(""); const [resolution, setResolution] = useState("");
  const [summary, setSummary] = useState<JourneySummary | null>(null); const [card, setCard] = useState<JourneyCard | null>(null);
  const [errorMessage, setErrorMessage] = useState(""); const [requestId, setRequestId] = useState(""); const [hydrated, setHydrated] = useState(false);
  const [audioStatus, setAudioStatus] = useState<AudioStatus>("idle"); const audioRef = useRef<HTMLAudioElement | null>(null); const audioUrlRef = useRef<string | null>(null);

  // Session storage is an external source; this one-time hydration intentionally restores its snapshot.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { try { const raw = sessionStorage.getItem(SESSION_KEY); if (raw) { const s = JSON.parse(raw) as SavedJourney; const interruptedEntry = s.phase === "loading" && !s.scene; setGoal(s.goal || ""); setPhase(interruptedEntry ? "map" : s.phase === "loading" || s.phase === "resolving" ? "island" : s.phase === "generating_end" ? "ending" : s.phase); setMemory(interruptedEntry ? null : s.memory); setScene(s.scene); setAnswer(s.answer || ""); setResolution(s.resolution || ""); setSummary(s.summary); setCard(s.card); if (interruptedEntry) setErrorMessage("The first crossing was interrupted. Your Ithaca is preserved; begin again when ready."); } } catch { sessionStorage.removeItem(SESSION_KEY); } finally { setHydrated(true); } }, []);
  useEffect(() => { if (!hydrated || phase === "map") return; sessionStorage.setItem(SESSION_KEY, JSON.stringify({ goal, phase, memory, scene, answer, resolution, summary, card } satisfies SavedJourney)); }, [answer, card, goal, hydrated, memory, phase, resolution, scene, summary]);
  // A changed scene invalidates the browser audio resource and its playback state.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { audioRef.current?.pause(); if (audioUrlRef.current) URL.revokeObjectURL(audioUrlRef.current); audioRef.current = null; audioUrlRef.current = null; setAudioStatus("idle"); }, [scene?.narrative]);
  function recordError(error: unknown) { const e = error as Error & { requestId?: string }; setErrorMessage(e.message || "The sea has not answered."); setRequestId(e.requestId || ""); }

  async function beginJourney() { const homeGoal = goal.trim(); if (!homeGoal) return; setErrorMessage(""); setPhase("loading"); const initial = createJourneyMemory(homeGoal); setMemory(initial); try { setScene(await requestHomer<HomerScene>({ phase: "enter", islandIndex: 0, homeGoal, timeline: [] })); setPhase("island"); } catch (e) { setPhase("map"); recordError(e); } }
  async function resolveAnswer() {
    const playerInput = answer.trim(); if (!playerInput || !memory || phase === "resolving") return;
    const island = getIsland(memory.currentIsland); if (!island) return; setErrorMessage(""); setPhase("resolving");
    try {
      const transition = await requestHomer<HomerTransition>({ phase: "resolve", islandIndex: memory.currentIsland, homeGoal: memory.homeGoal, timeline: memory.timeline, playerInput });
      const updated = resolveIsland(memory, island, transition.action_tag, playerInput); setMemory(updated); setResolution(transition.resolution); setAnswer("");
      if (updated.ending) { setScene({ narrative: transition.next_narrative, question: transition.next_question }); setPhase("ending"); return; }
      setScene({ narrative: transition.next_narrative, question: transition.next_question }); setPhase("island");
    } catch (e) { setPhase("island"); recordError(e); }
  }
  async function generateEnding() { if (!memory || phase === "generating_end") return; setErrorMessage(""); setPhase("generating_end"); try { const nextSummary = summary || await requestHomer<JourneySummary>({ phase: "summary", memory }); setSummary(nextSummary); const nextCard = await requestHomer<JourneyCard>({ phase: "card", memory, summary: nextSummary.summary }); setCard(nextCard); setPhase("ending"); } catch (e) { setPhase("ending"); recordError(e); } }
  async function hearHomer() { if (!scene || audioStatus === "loading") return; if (audioStatus === "playing" && audioRef.current) { audioRef.current.pause(); setAudioStatus("ready"); return; } if (audioStatus === "ready" && audioRef.current) { try { await audioRef.current.play(); setAudioStatus("playing"); } catch { setAudioStatus("error"); } return; } setAudioStatus("loading"); try { const response = await fetch("/api/homer/audio", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: `${scene.narrative} ${scene.question}` }) }); if (!response.ok) throw new Error(); const url = URL.createObjectURL(await response.blob()); audioUrlRef.current = url; const audio = new Audio(url); audioRef.current = audio; audio.onended = () => setAudioStatus("ready"); audio.onerror = () => setAudioStatus("error"); await audio.play(); setAudioStatus("playing"); } catch { setAudioStatus("error"); } }
  function resetJourney() { audioRef.current?.pause(); if (audioUrlRef.current) URL.revokeObjectURL(audioUrlRef.current); sessionStorage.removeItem(SESSION_KEY); setGoal(""); setPhase("map"); setMemory(null); setScene(null); setAnswer(""); setResolution(""); setSummary(null); setCard(null); setErrorMessage(""); setRequestId(""); }

  if (phase === "map") return <Map goal={goal} setGoal={setGoal} begin={beginJourney} error={errorMessage} />;
  if (!memory || !scene || phase === "loading") return <main className="journey voyage-loading"><p className="eyebrow">THE FIRST SHORE</p><h1>The map remembers your name.</h1><p>Homer gathers the words of your return.</p></main>;
  if (memory.ending) return <Ending memory={memory} scene={scene} summary={summary} card={card} phase={phase} generate={generateEnding} reset={resetJourney} error={errorMessage} />;

  const island = getIsland(memory.currentIsland); const index = memory.currentIsland;
  return <main className="journey"><header className="journey-top"><span className="brand">ODYSSEY <small>返鄉之旅</small></span><span className="goal-label">RETURNING TO <b>{memory.homeGoal}</b></span><span className="island-count">{String(index + 1).padStart(2, "0")} / 14</span></header><div className="progress"><span style={{ width: `${((index + 1) / 14) * 100}%` }} /></div><section className="island-layout" key={island.id}><div className={`island-art island-art-${island.id}`}><img src={ISLAND_ART[island.id]} alt={`${island.name}, ${island.epithet}`}/><div className="island-art-veil"/><div className="art-overlay"><span>SHORE {String(index + 1).padStart(2, "0")}</span><strong>{island.epithet}</strong></div></div><article className="narrative"><p className="eyebrow">ISLAND {String(index + 1).padStart(2, "0")} · {island.name.toUpperCase()}</p><h1>{island.name}</h1>{resolution && <p className="resolution">THE SEA REMEMBERS · {resolution}</p>}<p className="story" aria-live="polite">{scene.narrative}</p><AudioButton status={audioStatus} play={hearHomer}/><p className="island-question">{scene.question}</p><label className="answer-label" htmlFor="answer">THE TRAVELER SPEAKS</label><textarea id="answer" value={answer} onChange={(e) => setAnswer(e.target.value)} placeholder="Leave a few words for the sea…" disabled={phase === "resolving"}/><div className="journey-actions"><button className="answer-shore" onClick={resolveAnswer} disabled={phase === "resolving" || !answer.trim()}>{phase === "resolving" ? "THE SEA REMEMBERS…" : island.id === "ithaca" ? "COMPLETE THE RETURN" : "ANSWER THE SHORE"}</button>{errorMessage && <ErrorBox message={errorMessage} requestId={requestId} retry={resolveAnswer}/>}<button className="new-voyage" onClick={resetJourney}>START A NEW JOURNEY</button></div></article></section></main>;
}

function Map({ goal, setGoal, begin, error }: { goal: string; setGoal: (v: string) => void; begin: () => void; error: string }) { return <main className="landing map-world"><div className="map-plane"><img className="world-map" src="/odyssey-map.png" alt="The fourteen shores of the Aegean world"/><div className="island-layer" aria-hidden="true">{ISLANDS.map((island, i) => <button type="button" key={island.id} className={`island-node node-${i + 1}${i === 0 ? " is-start" : ""}`}><b>{island.name.toUpperCase()}</b></button>)}<span className="ship-token"/></div></div><div className="map-wash"/><header className="world-title"><span>ODYSSEY</span><i>✦　返 鄉 之 旅　✦</i></header><section className="world-entry"><h1>What are you trying to return to?</h1><p>Fourteen islands.<br/>One question at every shore.<br/><em>The map never changes. You will.</em></p><div className="world-form"><input aria-label="Your return goal" value={goal} onChange={(e) => setGoal(e.target.value)} onKeyDown={(e) => e.key === "Enter" && begin()} placeholder="Speak your Ithaca…"/><button onClick={begin}>BEGIN YOUR ODYSSEY <span>→</span></button></div>{error && <p className="map-error" role="alert">{error} <button onClick={begin}>TRY AGAIN</button></p>}</section><footer className="world-mark"><span>14 ISLANDS</span><span>✦</span><span>ONE JOURNEY</span><span>✦</span><span>COUNTLESS TRUTHS</span></footer></main>; }
function AudioButton({ status, play }: { status: AudioStatus; play: () => void }) { return <div className="homer-audio"><img className="homer-medallion" src="/assets/homer-medallion.webp" alt="" aria-hidden="true"/><div className="homer-audio-controls"><button type="button" onClick={play} disabled={status === "loading"}>{status === "loading" ? "SUMMONING HOMER…" : status === "playing" ? "PAUSE HOMER" : status === "ready" ? "PLAY HOMER" : "HEAR HOMER"}</button><small>Homer’s voice is AI-generated. The written words remain the record.</small>{status === "error" && <p role="alert">His voice was lost at sea. The journey may continue. <button onClick={play}>TRY AGAIN</button></p>}</div></div>; }
function ErrorBox({ message, requestId, retry }: { message: string; requestId: string; retry: () => void }) { return <div className="journey-error" role="alert"><strong>{message}</strong><span>Your answer has been preserved.</span>{requestId && <small>Sea mark: {requestId}</small>}<button onClick={retry}>TRY THE CROSSING AGAIN</button></div>; }
function Ending({ memory, scene, summary, card, phase, generate, reset, error }: { memory: JourneyMemory; scene: HomerScene; summary: JourneySummary | null; card: JourneyCard | null; phase: Phase; generate: () => void; reset: () => void; error: string }) { const calypso = memory.ending === "calypso"; const quote = card?.quote.replace(/^[\s"“”']+|[\s"“”']+$/g, ""); return <main className={`ending ending-${memory.ending}`}><div className="ending-intro"><div className="ending-seal">✦</div><p className="eyebrow">{calypso ? "A VALID ENDING · CALYPSO" : "THE RETURN · ITHACA"}</p><h1>{calypso ? "The sea goes on without you." : "Ithaca remembers."}</h1><p className="ending-lede">{scene.narrative}</p>{!card && <button className="restart" onClick={generate} disabled={phase === "generating_end"}>{phase === "generating_end" ? "HOMER GATHERS THE JOURNEY…" : "REVEAL MY JOURNEY"}</button>}{error && <p className="journey-end-error">{error} Your journey remains safe. <button onClick={generate}>TRY AGAIN</button></p>}</div>{summary && <section className="journey-summary"><p className="card-label">JOURNEY SUMMARY</p><p>{summary.summary}</p></section>}{card && <section className="card"><div className="card-heading"><img className="journey-card-crest" src="/assets/journey-card-crest.webp" alt="" aria-hidden="true"/><div><p className="card-label">JOURNEY CARD</p><h2>{card.title}</h2></div></div><dl className="journey-card-fields"><div><dt>STRENGTH</dt><dd>{card.strength}</dd></div><div><dt>TEMPTATION</dt><dd>{card.temptation}</dd></div><div><dt>TURNING POINT</dt><dd>{card.turningPoint}</dd></div><div><dt>TRUE ITHACA</dt><dd>{card.ithaca}</dd></div></dl><blockquote>“{quote}”</blockquote><p className="card-shores">{memory.timeline.length} SHORES · ONE RETURN</p></section>}<p className="timeline-note">{memory.timeline.length} shores recorded · The Journey Memory is intact.</p><button className="restart" onClick={reset}>BEGIN ANOTHER ODYSSEY</button></main>; }
